replicas: 2
gcp:
  databaseInstance: ent-nanna-dev:europe-west1:nanna-db-pg13

chouette:
  service: http://chouette.dev.entur.internal

ingress:
  domain: .dev.entur.io
  providers:
    name: timetable-admin-v1-providers

organisation:
  service: http://baba.dev.entur.internal

roleAssignmentExtractor: baba

auth0:
  entur:
    internal:
      url: https://internal.dev.entur.org/
      audience: https://api.dev.entur.io
    partner:
      url: https://partner.dev.entur.org/
      audience: https://api.dev.entur.io,https://portal.dev.entur.org

oauth2:
  client:
    id: U36z7scHWwDihVMZdPRlWP6CZjSY38XX
    url: https://internal.dev.entur.org/oauth/token
    audience: https://api.dev.entur.io

monitoringEnabled: true
