replicas: 2
gcp:
  databaseInstance: ent-nanna-tst:europe-west1:nanna-db-pg13

chouette:
  service: http://chouette.tst.entur.internal

ingress:
  domain: .staging.entur.io
  providers:
    name: timetable-admin-v1-providers

organisation:
  service: http://baba.tst.entur.internal

roleAssignmentExtractor: baba

auth0:
  entur:
    internal:
      url: https://internal.staging.entur.org/
      audience: https://api.staging.entur.io
    partner:
      url: https://partner.staging.entur.org/
      audience: https://api.staging.entur.io

oauth2:
  client:
    id: zRXrdCvSIGNHkC2UtM4JgVvyCtTllRgo
    url: https://internal.staging.entur.org/oauth/token
    audience: https://api.staging.entur.io


monitoringEnabled: true

